import { motion as m } from "framer-motion";
import Head from "next/head";
import Image from "next/image";

const bars = Array.from({ length: 20 }, (_, i) => i / 14);

export default function Intro() {
    return (
        <>
            <Head>
                <title>Recyclonaut</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {/* <div className="relative flex justify-center h-screen overflow-hidden">
                <m.div
                    className="w-2 bg-amber-50 absolute bottom-0"
                    initial={{ height: "0vh", width: "0.5rem" }}
                    animate={{ height: "100vh", width: "100vw" }}
                    transition={{
                        height: { duration: 1, delay: 2 },
                        width: { duration: 0.5, delay: 3 }
                    }}
                />

                <m.div
                    className="absolute bottom-0"
                    initial={{ y: 0 }}
                    animate={{ y: "-100vh" }}
                    transition={{
                        duration: 1,
                        delay: 2,
                    }}
                >
                    <Image src={"/rocket.svg"} width={100} height={100} alt="Rocket" />
                </m.div>
            </div> */}


            {/* Bars */}
            {bars.map((t, i) => (
                <m.div
                    key={i}
                    className="w-full h-6 bg-amber-50 flex justify-center items-center"
                    initial={{ height: 0 }}
                    animate={{ height: "100vh" }}
                    transition={{
                        duration: 0.9,
                        delay: 1 + t + 2,
                        ease: "easeInOut"
                    }}
                />
            ))}
        </>
    );
}
