import { motion as m } from "framer-motion";
import Head from "next/head";
import Image from "next/image";

const bars = Array.from({ length: 20 }, (_, i) => i / 19);

export default function Intro() {
    return (
        <>
            <Head>
                <title>Recyclonaut</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <div className="relative flex justify-center h-screen overflow-hidden">
                <m.div
                    className="absolute bottom-0 z-10"
                    initial={{ y: 0 }}
                    animate={{ y: "-100vh" }}
                    transition={{
                        duration: 1.8,
                        delay: 3.5,
                        ease: "easeInOut"
                    }}
                >
                    <Image
                        src="/rocket.svg"
                        width={100}
                        height={100}
                        alt="Rocket"

                    />
                </m.div>

                {bars.map((t, i) => (
                    <m.div
                        key={i}
                        className="absolute left-0 w-full bg-amber-50 h-16"
                        style={{ bottom: `${i * 5}%` }}
                        initial={{ scaleX: 0 }}
                        animate={{ scaleX: 1 }}
                        transition={{
                            duration: 1,
                            delay: 4 + t,
                            ease: "easeInOut"
                        }}
                    />
                ))}
            </div>

        </>
    );
}
