import { motion as m } from "framer-motion";
import Head from "next/head";
import Image from "next/image";

// ─── TIMING ──────────────────────────────────────────────
const rocketDelay = 2;
const rocketDuration = 4;
const trailDelay = 0.6; // how far behind the rocket the bars start

// normalized 0 → 1 for clean timing math
const bars = Array.from({ length: 20 }, (_, i) => i / 19);

export default function Test() {
    return (
        <>
            <Head>
                <title>Recyclonaut</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <div className="relative flex justify-center h-screen overflow-hidden">
                {/* 🚀 ROCKET */}
                <m.div
                    className="absolute bottom-0 z-10"
                    initial={{ y: 0 }}
                    animate={{ y: "-100vh" }}
                    transition={{
                        duration: 1.8,
                        delay: 3.5,
                        ease: "easeInOut"
                    }}
                >
                    <Image
                        src="/rocket.svg"
                        width={100}
                        height={100}
                        alt="Rocket"

                    />
                </m.div>

                {/* 🟨 TRAILING BARS */}
                {bars.map((t, i) => (
                    <m.div
                        key={i}
                        className="absolute left-0 w-full bg-amber-50 h-16"
                        style={{ bottom: `${i * 5}%` }}
                        initial={{ scaleX: 0 }}
                        animate={{ scaleX: 1 }}
                        transition={{
                            duration: 1,
                            delay: rocketDelay + t + 2,
                            ease: "easeInOut"
                        }}
                    />
                ))}
            </div>

        </>
    );
}
