import { motion as m } from "framer-motion";
import Head from "next/head";
import Image from "next/image";

const rocketDelay = 1.8;
const rocketDuration = 2.5;

const bars = Array.from({ length: 20 }, (_, i) => i / 14);

export default function Transition() {
    return (
        <>
            <Head>
                <title>Recyclonaut</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <div className="relative flex items-center justify-start h-screen overflow-hidden">
                {/* Rocket */}
                <m.div
                    className="absolute left-0 z-10"
                    initial={{ x: -120 }}
                    animate={{ x: "110vw" }}
                    transition={{
                        duration: rocketDuration,
                        delay: 3.2,
                        ease: "easeInOut"
                    }}
                >
                    <Image
                        src="/rocket.svg"
                        width={100}
                        height={100}
                        alt="Rocket"
                        style={{ transform: "rotate(90deg)" }}
                    />
                </m.div>

                {/* Bars */}
                {bars.map((t, i) => (
                    <m.div
                        key={i}
                        className="w-full h-6 bg-amber-50 flex justify-center items-center"
                        initial={{ height: 0 }}
                        animate={{ height: "100vh" }}
                        transition={{
                            duration: 0.9,
                            delay: rocketDelay + t + 2,
                            ease: "easeInOut"
                        }}
                    />
                ))}
            </div>
        </>
    );
}
