import "@/styles/globals.css";
import Head from 'next/head'
import { useRouter } from 'next/router'

import { AnimatePresence } from 'framer-motion'

export default function App({ Component, pageProps }) {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Recyclonaut</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <AnimatePresence mode="wait">
          <Component key={router.asPath} {...pageProps} />;
        </AnimatePresence>
      </main>

    </>

  )


}
