import { motion as m } from "framer-motion";
import Head from "next/head";
import Image from "next/image";
import Intro from "@/components/intro";
import Transition from "@/components/transition";
import Test from "@/components/test";

export default function Home() {
  return (
    <>
      <Head>
        <title>Recyclonaut</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/logo.svg" /> logo soon */}
      </Head>
      <Test />
    </>
  );
}
